[package]
name = "other-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
glam = "0.25.0"
image = "0.24.8"
indicatif = "0.17.7"
